### PR TITLE
Bump linter

### PR DESCRIPTION
**Pull request by lasiar**

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm curious

Wouldn't dependabot have bumped it?

I'm unsure as it's a simple parameter of golangci-lint action.

Or is it because you didn't want to wait for the weekly dependabot to be triggered ?

Thanks

**Comment by lasiar** [comment]
Hi, @ccoVeille!

Yes, this is just parameter, dependabot cannot work with them

**Comment by ccoVeille** [comment]
> Hi, @ccoVeille!
> 
> Yes, this is just parameter, dependabot cannot work with them
> 
> 

Thanks for confirmation

**Comment by ccoVeille** [comment]
Just checked code and documentation

You could use `latest` https://github.com/golangci/golangci-lint-action

**Comment by ccoVeille** [comment]
The same way could use `stable`+ `oldstable` for go-version with setup-go

https://github.com/marketplace/actions/setup-go-environment#using-stableoldstable-aliases

**Comment by ccoVeille** [comment]
I think `renovate` GHA not would be able to catch this kind of upgrade, you can have a look here

https://github.com/deepmap/oapi-codegen/pull/1603

Did you ever try it?

But using  `latest` as I suggested in a previous message could also be OK

Any thoughts about it ? @lasiar

**Pull request merged**
