### PR TITLE
ci(go): add tip version

### PR DESCRIPTION
**Pull request by lasiar**

### CODE REVIEW

**Comment by ccoVeille** [comment]
Isn't any action about this?

**Comment by ccoVeille** [comment]
Any reason to test in the tip ? I didn't see it often? Are you expecting different behavior?

**Comment by lasiar** [comment]
Sometimes go team broken backward compatibility. I want to know about this as early as possible.

And GitHub run tests every week, by schedule [code](https://github.com/lasiar/canonicalheader/blob/main/.github/workflows/go.yml#L9).


Maybe this is too much  :)

**Comment by ccoVeille** [comment]
> Hi, @ccoVeille
> Sometimes go team broken backward compatibility. I want to know about this as early as possible.
> 
> And GitHub run tests every week, by schedule [code](https://github.com/lasiar/canonicalheader/blob/main/.github/workflows/go.yml#L9).
> 
> 
> Maybe this is too much  :)
> 
> 

Thanks for your detailed reply

**Pull request merged**
